Added scan type parameter and scan duration parameter for customizing the scan runs.

diff --git a/tekton/base/tasks/owasp-scanner.yaml b/tekton/base/tasks/owasp-scanner.yaml
--- a/tekton/base/tasks/owasp-scanner.yaml
+++ b/tekton/base/tasks/owasp-scanner.yaml
@@ -17,13 +17,37 @@ spec:
 
   workspaces:
     - name: source
+    - name: owasp-settings
+      optional: true
+      mountPath: /zap/wrk
   params:
     - name: TARGET_URL
       description: Host URL where the sonarqube server is running
       default: "https://example.com"
+    - name: SCAN_TYPE
+      description: Options include quick or full.
+      default: "quick"
+    - name: SCAN_DURATION
+      description: The duration of the OWASP scan.
+      default: "1"
   steps:
-    - name: owasp-quick-scan
+    - name: owasp-scan
       image: owasp/zap2docker-stable
       workingDir: $(workspaces.source.path)
-      command:
-        - zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' $(params.TARGET_URL)
+      script: |
+        #!/bin/bash
+
+        if [ $(params.SCAN_TYPE) = "quick" ]
+        then
+          echo "performing quick scan"
+          zap-baseline.py -t $(params.TARGET_URL) -d -g gen.conf -J owasp-quick-results.json -m $(params.SCAN_DURATION) -I
+          cat $(workspaces.owasp-settings.path)/owasp-quick-results.json
+        elif [ $(params.SCAN_TYPE) = "full" ]
+        then
+          echo "performing full scan"
+          zap-full-scan.py -t $(params.TARGET_URL) -d -g gen.conf -J owasp-full-results.json -m $(params.SCAN_DURATION) -I
+          cat $(workspaces.owasp-settings.path)/owasp-full-results.json
+        else
+          echo "ERROR: Scan type must be set to quick or full."
+          exit 1
+        fi
