add oc deploy

diff --git a/.github/workflows/oc-build-deploy.yaml b/.github/workflows/oc-build-deploy.yaml
--- a/.github/workflows/oc-build-deploy.yaml
+++ b/.github/workflows/oc-build-deploy.yaml
@@ -24,15 +24,10 @@
 
 # 👋 Visit our GitHub organization at https://github.com/redhat-actions/ to see our actions and provide feedback.
 
-name: helm-build-deploy
+name: oc-build-deploy
 
 env:
-  NAME: nginx-web
-  IMAGE: gregnrobinson/bcgov-nginx-demo
-  TAG: latest
-  NAMESPACE: nginx-demo
-  RELEASE: nginx-web
-  WORK_DIR: ./demo/nginx
+  WORK_DIR: ./demo/flask-web
   # 🖊️ EDIT your repository secrets to log into your OpenShift cluster and set up the context.
   # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
   # To get a permanent token, refer to https://github.com/redhat-actions/oc-login/wiki/Using-a-Service-Account-for-GitHub-Actions
@@ -43,7 +38,7 @@ env:
   OPENSHIFT_NAMESPACE: "default"
 
   # 🖊️ EDIT to set a name for your OpenShift app, or a default one will be generated below.
-  APP_NAME: "bcgov-nginx-demo"
+  APP_NAME: "flask-demo-app"
 
   # 🖊️ EDIT with the port your application should be accessible on.
   # If the container image exposes *exactly one* port, this can be left blank.
@@ -74,11 +69,6 @@ jobs:
       SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
 
     steps:
-    - name: Setup Tailscale
-      uses: tailscale/github-action@main
-      with:
-        authkey: ${{ secrets.TAILSCALE_API_KEY }}
-        #version: 1.10.2
     - name: Check for required secrets
       uses: actions/github-script@v4
       with:
@@ -142,7 +132,7 @@ jobs:
         # Or, perform a source-to-image build using https://github.com/redhat-actions/s2i-build
         # Otherwise, point this to your Dockerfile/Containerfile relative to the repository root.
         dockerfiles: |
-          ./demo/nginx/Dockerfile
+          ./demo/flask-web/Dockerfile
 
     # https://github.com/redhat-actions/push-to-registry#readme
     - name: Push to registry
@@ -155,34 +145,41 @@ jobs:
         username: ${{ env.IMAGE_REGISTRY_USER }}
         password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
 
-    - name: Determine image tags
-      if: env.IMAGE_TAGS == ''
-      run: |
-        echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
+    # The path the image was pushed to is now stored in ${{ steps.push-image.outputs.registry-path }}
+    - name: Install oc
+      uses: redhat-actions/openshift-tools-installer@v1
+      with:
+        oc: 4
 
-    #- name: Setup SSH
-    #  id: ssh
-    #  env:
-    #    SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-    #  run: |
-    #    set -x
-    #    mkdir -p ~/.ssh
-    #    host="dev-ubuntu-1.gregnrobinson.github.beta.tailscale.net"
-    #    host6=$(tailscale ip -6 $host)
-    #    ssh-keyscan ${host6} >> ~/.ssh/known_hosts
-    #    printf "%s" "${SSH_KEY}" > ~/.ssh/key
-    #    chmod 600 ~/.ssh/key
-    #    ping -c 2 ${host6}
-#
-    #    ssh greg@dev-ubuntu-1.gregnrobinson.github.beta.tailscale.net "oc login -u kubeadmin https://api.crc.testing:6443 &&\
-    #    cd ./security-pipeline-templates &&\
-    #    git pull &&\
-    #    helm upgrade --install nginx-web -f ./demo/nginx/helm/values.yaml ./demo/nginx/helm"
-    #
-     #kubectl port-forward deployments/nginx-web 8081:80
-    - name: Deploy using Helm
+    # https://github.com/redhat-actions/oc-login#readme
+    - name: Log in to OpenShift
+      uses: redhat-actions/oc-login@v1
+      with:
+        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+        insecure_skip_tls_verify: true
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+
+    # This step should create a deployment, service, and route to run your app and expose it to the internet.
+    # https://github.com/redhat-actions/oc-new-app#readme
+    - name: Create and expose app
+      id: deploy-and-expose
+      uses: redhat-actions/oc-new-app@v1
+      with:
+        app_name: ${{ env.APP_NAME }}
+        image: ${{ steps.push-image.outputs.registry-path }}
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+        port: ${{ env.APP_PORT }}
+
+    - name: Print application URL
+      env:
+        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
       run: |
-        oc login -u kubeadmin https://api.crc.testing:6443 &&\
-        cd ./security-pipeline-templates &&\
-        git pull &&\
-        helm upgrade --install nginx-web -f ./demo/nginx/helm/values.yaml ./demo/nginx/helm"
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        echo
+        echo "======================== Your application is available at: ========================"
+        echo ${{ env.ROUTE }}
+        echo "==================================================================================="
+        echo
+        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
