add helm deploy

diff --git a/.github/workflows/oc-build-deploy.yaml b/.github/workflows/oc-build-deploy.yaml
--- a/.github/workflows/oc-build-deploy.yaml
+++ b/.github/workflows/oc-build-deploy.yaml
@@ -226,41 +226,27 @@ jobs:
 
             affinity: {}
   
-    
-    
-    
-    
-    
-    
-    
-    
-    
-    
-    
-    
-    
-    
-    
-    # This step should create a deployment, service, and route to run your app and expose it to the internet.
-    # https://github.com/redhat-actions/oc-new-app#readme
-    - name: Create and expose app
-      id: deploy-and-expose
-      uses: redhat-actions/oc-new-app@v1
-      with:
-        app_name: ${{ env.APP_NAME }}
-        image: ${{ steps.push-image.outputs.registry-path }}
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-        port: ${{ env.APP_PORT }}
-
-    - name: Print application URL
-      env:
-        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
-      run: |
-        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-        echo
-        echo "======================== Your application is available at: ========================"
-        echo ${{ env.ROUTE }}
-        echo "==================================================================================="
-        echo
-        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+  #  # This step should create a deployment, service, and route to run your app and expose it to the internet.
+  #  # https://github.com/redhat-actions/oc-new-app#readme
+  #  - name: Create and expose app
+  #    id: deploy-and-expose
+  #    uses: redhat-actions/oc-new-app@v1
+  #    with:
+  #      app_name: ${{ env.APP_NAME }}
+  #      image: ${{ steps.push-image.outputs.registry-path }}
+  #      namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+  #      port: ${{ env.APP_PORT }}
+#
+  #  - name: Print application URL
+  #    env:
+  #      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+  #      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+  #    run: |
+  #      [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+  #      echo
+  #      echo "======================== Your application is available at: ========================"
+  #      echo ${{ env.ROUTE }}
+  #      echo "==================================================================================="
+  #      echo
+  #      echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+#
